# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedu_calendar', '0002_calendarevent_classify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='classify',
            field=models.CharField(choices=[('과행사', '과행사'), ('개인행사', '개인행사'), ('연중행사', '연중행사')], default='과행사', max_length=20),
        ),
    ]
