# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedu_calendar', '0004_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='search',
        ),
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ('start',)},
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='start',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
