# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 08:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comedu_calendar', '0004_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='search',
        ),
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ('start',)},
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 15, 8, 15, 5, 814594, tzinfo=utc), verbose_name='Start Time'),
        ),
    ]
