# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedu_calendar', '0005_auto_20170215_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
    ]
