# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comedu_calendar', '0006_auto_20170216_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='start_time',
        ),
    ]
