# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 11:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comedu_calendar', '0007_auto_20170216_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='end',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
