# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedu_calendar', '0008_auto_20170220_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
    ]
