"""
Django settings for comedu project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')7e2!v6$a8l78)l$ohu*-@^fclfa0uttpk%+t(4#!l#q7krhn*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

LOGIN_REDIRECT_URL = '/'

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'customuser.MyUser'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'customuser',

    #for calendar
    'comedu_calendar',

    'blog',
    'django_summernote',
    'polls',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'comedu.urls'
##add for calendar
BOWER_COMPONENTS_ROOT = '/PROJECT_ROOT/components/'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]

WSGI_APPLICATION = 'comedu.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
##add for calendar
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'
##add for calendar
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
SUMMERNOTE_CONFIG = {

    # # Set text direction : 'left to right' is default.
    # 'direction': 'ltr',
    #
    # # Change editor size
    # 'width': '100%',
    # 'height': '480',
    #
    # # Use proper language setting automatically (default)
    # 'lang': None,
    #
    # # Or, set editor language/locale forcely
    # 'lang': 'ko-KR',
    #
    # # Customize toolbar buttons
    # 'toolbar': [
    #     ['style', ['style']],
    #     ['style', ['bold', 'italic', 'underline', 'clear']],
    #     ['para', ['ul', 'ol', 'height']],
    #     ['insert', ['link']],
    # ],
    #
    # # Need authentication while uploading attachments.
    # 'attachment_require_authentication': True,
    #
    # # Set `upload_to` function for attachments.
    # 'attachment_upload_to': my_custom_upload_to_func(),
    #
    # # Set custom storage class for attachments.
    # 'attachment_storage_class': 'my.custom.storage.class.name',
    #
    # # Set custom model for attachments (default: 'django_summernote.Attachment')
    # 'attachment_model': 'my.custom.attachment.model', # must inherit 'django_summernote.AbstractAttachment'
    #
    # # Set common css/js media files
    # 'external_css': (
    #     '//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css',
    # ),
    # 'external_js': (
    #     '//code.jquery.com/jquery-1.9.1.min.js',
    #     '//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js',
    # ),
    # 'internal_css': (
    #     static_url('django_summernote/summernote.css'),
    # ),
    # 'internal_js': (
    #     static_url('django_summernote/jquery.ui.widget.js'),
    #     static_url('django_summernote/jquery.iframe-transport.js'),
    #     static_url('django_summernote/jquery.fileupload.js'),
    #     static_url('django_summernote/summernote.min.js'),
    # ),
    #
    # # You can add custom css/js for SummernoteWidget.
    # 'css': (
    # ),
    # 'js': (
    # ),
    #
    # # And also for SummernoteInplaceWidget.
    # # !!! Be sure to put {{ form.media }} in template before initiate summernote.
    # 'css_for_inplace': (
    # ),
    # 'js_for_inplace': (
    # ),
    #
    # # You can disable file upload feature.
    # 'disable_upload': False,
    #
    # # Codemirror as codeview
    # 'codemirror': {
    #         # Please visit http://summernote.org/examples/#codemirror-as-codeview
    #         'theme': 'monokai',
    # },

}
