# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_auto_20170207_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
