# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 09:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('찬성', models.IntegerField(blank=True, null=True)),
                ('반대', models.IntegerField(blank=True, null=True)),
                ('기권', models.IntegerField(blank=True, null=True)),
                ('작성자', models.CharField(blank=True, max_length=100)),
                ('분류', models.CharField(blank=True, choices=[('ergent', '긴급'), ('events', '행사'), ('comedu', '과사')], default='ergent', max_length=10)),
            ],
        ),
    ]
